version: '3'
services:
  mysql_vivid:
    container_name: mysql_vivid
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: "byuk"
      MYSQL_PASSWORD: "byuk"
      MYSQL_DATABASE: "vivid"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
  redis_note:
    container_name: redis_note
    image: redis
    ports:
      - "6379:6379"
  redis_user:
    container_name: redis_user
    image: redis
    ports:
      - "6380:6379"